(Issue #5) Make sure that all OpenMPI Ubuntu packages installed.

diff --git a/.github/workflows/test_book.yml b/.github/workflows/test_book.yml
--- a/.github/workflows/test_book.yml
+++ b/.github/workflows/test_book.yml
@@ -26,7 +26,7 @@ jobs:
     - name: Install OpenMPI
       run: |
            sudo apt-get update
-           sudo apt-get -y install openmpi-bin
+           sudo apt-get -y install openmpi-bin libopenmpi-dev
 
     - name: Setup python with tox
       run: |
@@ -37,6 +37,10 @@ jobs:
 
     - name: Build Jupyter Book
       run: |
+        which mpirun || echo "Cannot find the MPI installation"
+        which mpicxx || echo "Cannot find the MPI compiler wrapper"
+        mpicxx -show || echo "Cannot check the MPI wrapper specification"
+        echo " "
         pushd $CLONE_PATH
         tox -r -e book
         popd
